# Best from 40-parallel search: win_rate=0.693 idx=34
import os
os.environ.setdefault('PTCG_SUPPORTER', '355')
os.environ.setdefault('PTCG_ITEM', '339')
os.environ.setdefault('PTCG_BENCH', '302')
os.environ.setdefault('PTCG_EVOLVE', '302')
os.environ.setdefault('PTCG_ATTACH', '304')
os.environ.setdefault('PTCG_STADIUM', '310')
os.environ.setdefault('PTCG_ABILITY', '284')
os.environ.setdefault('PTCG_ATTACK_KO', '242')
os.environ.setdefault('PTCG_ATTACK', '218')
os.environ.setdefault('PTCG_RETREAT_BASE', '113')
os.environ.setdefault('PTCG_RETREAT_NO_ATK', '196')
os.environ.setdefault('PTCG_RETREAT_KO', '298')
os.environ.setdefault('PTCG_RETREAT_WALL', '370')
os.environ.setdefault('PTCG_GUST_BONUS', '51')
os.environ.setdefault('PTCG_WALL_PENALTY', '-420')
os.environ.setdefault('PTCG_WALL_ESCAPE', '300')
os.environ.setdefault('PTCG_ATTACH_WALL_BONUS', '80')
os.environ.setdefault('PTCG_ATTACH_WALL_PENALTY', '-15')
os.environ.setdefault('PTCG_BEACH_WALL', '357')
os.environ.setdefault('PTCG_FIGHTER_READY', '77')
os.environ.setdefault('PTCG_FIGHTER_NOT_READY', '-75')
os.environ.setdefault('PTCG_PRIZE_PENALTY', '16')
os.environ.setdefault('PTCG_ENABLE_BONUS', '26')
os.environ.setdefault('PTCG_PROGRESS_BONUS', '27')
os.environ.setdefault('PTCG_ACTIVE_BONUS', '7')
os.environ.setdefault('PTCG_PRIMARY_BONUS', '18')

from agents.main_tunable import agent
